Repository woowacourse-teams/2025-festabook, pull requests merged in 2025-07, with the labels that each got.

#15 [AN] 스타일 지정 및 Java버전 업데이트
  android/app/build.gradle.kts
  android/app/src/main/res/font/pretendard_bold.ttf
  android/app/src/main/res/font/pretendard_medium.ttf
  android/app/src/main/res/font/pretendard_regular.ttf
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
Labels: Feat, AN, Build

#30 [AN] 바텀 네비게이션 바 뷰 구현 및 공통 util 클래스 구현
  android/app/.gitignore
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/.gitkeep
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/.gitkeep
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/NetworkModule.kt
  android/app/src/main/java/com/daedan/festabook/data/model/.gitkeep
  android/app/src/main/java/com/daedan/festabook/data/repository/.gitkeep
  android/app/src/main/java/com/daedan/festabook/domain/model/.gitkeep
  android/app/src/main/java/com/daedan/festabook/domain/repository/.gitkeep
  android/app/src/main/java/com/daedan/festabook/presentation/common/BaseFragment.kt
  android/app/src/main/java/com/daedan/festabook/util/.gitkeep
  android/app/src/main/res/color/menu_bottom_navigation_color.xml
  android/app/src/main/res/drawable/ic_home.xml
  android/app/src/main/res/drawable/ic_map.xml
  android/app/src/main/res/drawable/ic_news.xml
  android/app/src/main/res/drawable/ic_schedule.xml
  android/app/src/main/res/drawable/ic_setting.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/menu/menu_bottom_navigation.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
  android/gradle.properties
  android/gradle/libs.versions.toml
Labels: Feat, AN

#24 [BE] 최상위 커스텀 예외 추가
  backend/src/main/java/com/daedan/festabook/global/exception/BusinessException.java
Labels: Feat, BE

#36 [AN] Andoid TargetSDK 변경
  android/app/build.gradle.kts
Labels: AN, Build

#9 [BE] Announcement 생성/조회 구현
  backend/src/main/java/com/daedan/festabook/FestabookApplication.java
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementResponse.java
  backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementResponses.java
  backend/src/main/java/com/daedan/festabook/announcement/infrastructure/AnnouncementJpaRepository.java
  backend/src/main/java/com/daedan/festabook/announcement/service/AnnouncementService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/service/AnnouncementServiceTest.java
Labels: Feat, BE

#16 [BE] Place 생성 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceCategory.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementResponses.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageResponses.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponses.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceAnnouncementJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceImageService.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceService.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceImageServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
Labels: Feat, BE

#52 [BE] OrganizationJpaRepository 추가, 설정 정보 global로 이동
  backend/src/main/java/com/daedan/festabook/global/argumentresolver/OrganizationId.java
  backend/src/main/java/com/daedan/festabook/global/argumentresolver/OrganizationIdArgumentResolver.java
  backend/src/main/java/com/daedan/festabook/global/config/WebMvcConfig.java
  backend/src/main/java/com/daedan/festabook/organization/infrastructure/OrganizationJpaRepository.java
  backend/src/test/java/com/daedan/festabook/global/config/WebMvcConfigTest.java
Labels: Feat, BE

#49 [BE] 일정 Swagger 및 그룹화 추가
  backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java
  backend/src/main/java/com/daedan/festabook/schedule/controller/ScheduleController.java
Labels: Docs, BE

#63 [BE] Swagger 전역 Organization Id 추가
  backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java
  backend/src/main/resources/application.yml
Labels: Docs, BE

#66 [BE] 공지에 고정된 공지 여부를 추가
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementResponse.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
Labels: Feat, BE

#60 [AN] 공지 컴포넌트 ui 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/presentation/common/BindingAdapter.kt
  android/app/src/main/res/drawable/bg_stroke_gray400_radius_10dp.xml
  android/app/src/main/res/drawable/ic_pin.xml
  android/app/src/main/res/drawable/ic_speaker.xml
  android/app/src/main/res/layout/item_notice.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#70 [BE] 플레이스 인수테스트 작성
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/test/java/com/daedan/festabook/orgnaization/domain/OrganizationFixture.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
Labels: BE, Test

#75 [BE] 일정 인수테스트 작성
  backend/src/main/java/com/daedan/festabook/schedule/domain/Event.java
  backend/src/main/java/com/daedan/festabook/schedule/dto/EventDateResponses.java
  backend/src/main/java/com/daedan/festabook/schedule/service/ScheduleService.java
  backend/src/test/java/com/daedan/festabook/global/config/WebMvcConfigTest.java
  backend/src/test/java/com/daedan/festabook/schedule/controller/ScheduleControllerTest.java
  backend/src/test/java/com/daedan/festabook/schedule/domain/EventDateFixture.java
  backend/src/test/java/com/daedan/festabook/schedule/domain/EventFixture.java
  backend/src/test/java/com/daedan/festabook/schedule/service/ScheduleServiceTest.java
Labels: BE, Test

#72 [AN] 일정화면 UI 구현
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/.gitkeep
  android/app/src/main/java/com/daedan/festabook/data/repository/ScheduleRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/.gitkeep
  android/app/src/main/java/com/daedan/festabook/domain/model/ScheduleEvent.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/ScheduleEventStatus.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/.gitkeep
  android/app/src/main/java/com/daedan/festabook/domain/repository/ScheduleRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/OnBookmarkCheckedListener.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabPageFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleItemViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/SchedulePagerAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/mapper/ScheduleEventMapper.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/model/ScheduleEventUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/model/ScheduleEventUiStatus.kt
  android/app/src/main/res/color/selector_schedule_tab_text_color.xml
  android/app/src/main/res/drawable/bg_gray900_radius_6dp.xml
  android/app/src/main/res/drawable/bg_schedule_stroke_1dp_radius_10dp.xml
  android/app/src/main/res/drawable/bg_schedule_stroke_blue400_radius_10dp.xml
  android/app/src/main/res/drawable/bg_stroke_gray900_radius_6dp.xml
  android/app/src/main/res/drawable/ic_bookmark.xml
  android/app/src/main/res/drawable/ic_bookmark_filled.xml
  android/app/src/main/res/drawable/ic_clock.xml
  android/app/src/main/res/drawable/ic_location.xml
  android/app/src/main/res/drawable/ic_schedule_circle_blue400.png
  android/app/src/main/res/drawable/ic_schedule_circle_gray300.png
  android/app/src/main/res/drawable/ic_schedule_circle_green400.png
  android/app/src/main/res/drawable/schedule_bg_gray900_radius_20dp.xml
  android/app/src/main/res/drawable/selector_schedule_tab_background.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_schedule.xml
  android/app/src/main/res/layout/fragment_schedule_tab_page.xml
  android/app/src/main/res/layout/item_schedule_tab.xml
  android/app/src/main/res/layout/item_schedule_tab_page.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: Feat, AN

#87 [AN] Gitbub Action 를 활용한 CI 설정 추가
  .github/workflows/ci-android.yml
Labels: CI/CD, AN

#94 [AN] 일정화면 디자인 변경
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabSelectedListener.kt
  android/app/src/main/res/layout/fragment_schedule.xml
  android/app/src/main/res/layout/item_schedule_tab.xml
Labels: Refactor, AN

#96 [BE] 전역 예외 핸들러 추가
  backend/src/main/java/com/daedan/festabook/global/exception/BusinessException.java
  backend/src/main/java/com/daedan/festabook/global/exception/GlobalExceptionHandler.java
  backend/src/test/java/com/daedan/festabook/global/exception/GlobalExceptionHandlerTest.java
Labels: Feat, BE

#91 [BE] Place API 합치기
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacePreviewResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacePreviewResponses.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponses.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceImageService.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
  backend/src/test/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepositoryTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceImageServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
Labels: Feat, BE

#103 [BE] 테스트용 데이터 data.sql 추가
  backend/src/main/resources/data.sql
Labels: Feat, Chore, BE

#101 [AN] 컨벤션 변경에 따른 리소스 파일 이름명 수정 및 클래스명 통일
  android/app/src/main/java/com/daedan/festabook/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/.gitkeep
  android/app/src/main/java/com/daedan/festabook/presentation/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/model/NoticeUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListBindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/adapter/PlaceListAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/adapter/PlaceListViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/dummy/DummyPlace.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCategory.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleItemViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/mapper/ScheduleEventMapper.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/model/ScheduleEventUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/model/ScheduleEventUiStatus.kt
  android/app/src/main/res/drawable/bg_gray400_radius_50dp.xml
  android/app/src/main/res/drawable/bg_gray900_radius_20dp.xml
  android/app/src/main/res/drawable/bg_stroke_blue400_radius_10dp.xml
  android/app/src/main/res/drawable/bg_stroke_green400_radius_10dp.xml
  android/app/src/main/res/drawable/btn_bookmark.xml
  android/app/src/main/res/drawable/btn_bookmark_selected.xml
  android/app/src/main/res/drawable/btn_bookmark_unselected.xml
  android/app/src/main/res/drawable/ic_bookmark_normal.xml
  android/app/src/main/res/drawable/ic_bookmark_selected.xml
  android/app/src/main/res/drawable/ic_circle_blue400.png
  android/app/src/main/res/drawable/ic_circle_gray300.png
  android/app/src/main/res/drawable/ic_circle_green400.png
  android/app/src/main/res/drawable/ic_place_list_location.xml
  android/app/src/main/res/drawable/selector_bg_gray900_radius_20.xml
  android/app/src/main/res/layout/fragment_news.xml
  android/app/src/main/res/layout/item_notice.xml
  android/app/src/main/res/layout/item_place_list.xml
  android/app/src/main/res/layout/item_place_list_header.xml
  android/app/src/main/res/layout/item_schedule_tab.xml
  android/app/src/main/res/layout/item_schedule_tab_page.xml
Labels: Refactor, AN

#100 [AN] 소식 화면 - 클릭 시 공지 확장 기능 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/OnNoticeClickListener.kt
  android/app/src/main/res/layout/fragment_news.xml
  android/app/src/main/res/layout/item_notice.xml
Labels: Feat, AN

#121 [BE] PR의 base branch가 main, backend이라면, 테스트를 실행하는 workflow 작성
  .github/workflows/backend-pr-test.yml
Labels: CI/CD, BE, Test

#127 [BE] 코드 래빗 도입 및 설정 추가
  .coderabbit.yaml
  android/code-style.md
  backend/code-style.md
Labels: Feat, BE

#109 [AN] 안드로이드 CI yml 파일 수정
  .github/workflows/ci-android.yml
  android/build.gradle.kts
  android/settings.gradle.kts
Labels: CI/CD, AN

#134 [AN] CodeRabbit 가이드 적용
  .coderabbit.yaml
  android/code-style.md
  backend/code-style.md
Labels: Feat, Chore, AN

#130 [BE] CodeRabbit 지침 수정
  .coderabbit.yaml
Labels: Chore, BE

#150 [BE] 예외 응답시 JSON 형태로 응답하도록 변경
  backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java
  backend/src/main/java/com/daedan/festabook/global/exception/BusinessException.java
  backend/src/main/java/com/daedan/festabook/global/exception/ExceptionResponse.java
  backend/src/main/java/com/daedan/festabook/global/exception/GlobalExceptionHandler.java
  backend/src/test/java/com/daedan/festabook/global/exception/GlobalExceptionHandlerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
Labels: Feat, BE

#142 [AN] 네이버 지도 화면 UI 구현
  .github/workflows/ci-android.yml
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/AnimationUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/PermissionUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListScrollBehavior.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListUserActionEvent.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/dummy/DummyMapData.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/CoordinateUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/InitialMapSettingUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCategory.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCoordinateUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/ClusterManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/ClusteringMarkerKey.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapScrollManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/OverlayImageManager.kt
  android/app/src/main/res/drawable/ic_bar.xml
  android/app/src/main/res/drawable/ic_booth.xml
  android/app/src/main/res/drawable/ic_food_truck.xml
  android/app/src/main/res/drawable/ic_smoking_area.xml
  android/app/src/main/res/drawable/ic_toilet.xml
  android/app/src/main/res/drawable/ic_trash.xml
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
  android/settings.gradle.kts
Labels: Feat, AN

#145 [AN] 일정 화면 SwipeRefreshLayout, Skeleton UI 적용
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabPageFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleViewModel.kt
  android/app/src/main/res/drawable/bg_gray300_radius_10dp.xml
  android/app/src/main/res/drawable/bg_gray300_radius_20dp.xml
  android/app/src/main/res/layout/fragment_schedule.xml
  android/app/src/main/res/layout/fragment_schedule_tab_page.xml
  android/app/src/main/res/layout/item_schedule_tab_page_skeleton.xml
  android/app/src/main/res/layout/item_schedule_tab_skeleton.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/themes.xml
  android/gradle/libs.versions.toml
Labels: Feat, AN

#162 [BE] 일정 상태 필드 삭제 및 계산 로직 추가
  backend/src/main/java/com/daedan/festabook/global/config/ClockConfig.java
  backend/src/main/java/com/daedan/festabook/schedule/domain/Event.java
  backend/src/main/java/com/daedan/festabook/schedule/domain/EventStatus.java
  backend/src/main/java/com/daedan/festabook/schedule/dto/EventResponse.java
  backend/src/main/java/com/daedan/festabook/schedule/dto/EventResponses.java
  backend/src/main/java/com/daedan/festabook/schedule/service/ScheduleService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/schedule/controller/ScheduleControllerTest.java
  backend/src/test/java/com/daedan/festabook/schedule/domain/EventFixture.java
  backend/src/test/java/com/daedan/festabook/schedule/domain/EventStatusTest.java
  backend/src/test/java/com/daedan/festabook/schedule/domain/EventTest.java
  backend/src/test/java/com/daedan/festabook/schedule/service/ScheduleServiceTest.java
Labels: Fix, BE

#185 [BE] Bookmark 일부 테스트명 변경
  backend/src/test/java/com/daedan/festabook/organization/controller/OrganizationBookmarkControllerTest.java
  backend/src/test/java/com/daedan/festabook/organization/service/OrganizationBookmarkServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceBookmarkControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceBookmarkServiceTest.java
Labels: BE, Test

#182 [BE] 예외 핸들러 예외 수정
  backend/src/main/java/com/daedan/festabook/global/exception/GlobalExceptionHandler.java
Labels: Fix, BE

#179 [AN] 공연 완료시 배경 색상 누락 수정
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleItemViewHolder.kt
Labels: Fix, AN

#164 [AN] 네이버 지도 마커 디자인 변동 및 Behavior 단위 dp로 변경
  .github/workflows/ci-android.yml
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListScrollBehavior.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/dummy/DummyMapData.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/ClusterManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/OverlayImageManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleItemViewHolder.kt
  android/app/src/main/res/drawable/ic_bar.xml
  android/app/src/main/res/drawable/ic_booth.xml
  android/app/src/main/res/drawable/ic_cluster_marker.xml
  android/app/src/main/res/drawable/ic_food_truck.xml
  android/app/src/main/res/drawable/ic_smoking_area.xml
  android/app/src/main/res/drawable/ic_toilet.xml
  android/app/src/main/res/drawable/ic_trash.xml
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/values/colors.xml
Labels: Fix, Feat, AN

#194 [FE] 지도 좌표 설정 페이지 구현
  frontend/src/components/map/MapSelector.tsx
  frontend/src/pages/MapSettingsPage.jsx
Labels: Feat, FE

#174 [AN] 플레이스 화면 서버 연동
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceDetailResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceDetailRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/PlaceService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/ApiClient.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/Place.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/PlaceCategory.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/PlaceDetail.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/PlaceDetailImage.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/PlaceDetailRepository.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/PlaceListRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceClickListener.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/adapter/PlaceListAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/adapter/PlaceListViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/dummy/DummyMapData.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/dummy/DummyPlace.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCategory.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCategoryUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCoordinateUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/ClusterManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/res/layout/item_place_list.xml
Labels: Feat, AN

#190 [AN] Notification 설정 및 FCM 연결
  .github/workflows/ci-android.yml
  android/.gitignore
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/.gitkeep
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/AppPreferencesManager.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/ApiResult.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/DeviceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/DeviceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/OrganizationBookmarkDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/OrganizationBookmarkDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/request/DeviceRegisterRequest.kt
  android/app/src/main/java/com/daedan/festabook/data/model/request/OrganizationBookmarkRequest.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/DeviceRegisterResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/OrganizationBookmarkResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/BookmarkRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/DeviceRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/DeviceService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/OrganizationBookmarkService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/ApiClient.kt
  android/app/src/main/java/com/daedan/festabook/data/util/ApiExtension.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/BookmarkRepository.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/DeviceRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/daedan/festabook/service/MyFirebaseMessagingService.kt
  android/app/src/main/java/com/daedan/festabook/service/NotificationHelper.kt
  android/app/src/main/java/com/daedan/festabook/util/PermissionHandler.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: Feat, AN

#199 [AN] 플레이스 상세 화면 서버 연동
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceDetailResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceDetailRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/PlaceService.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/Place.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/PlaceDetail.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/PlaceDetailImage.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/PlaceDetailRepository.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/PlaceListRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/model/ImageUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/model/PlaceDetailUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/model/PlaceDetailUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceUiModel.kt
  android/app/src/main/res/layout/fragment_place_detail.xml
  android/app/src/main/res/layout/item_place_list.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#208 [AN] 소식 화면 SwipeRefreshLayout 구현
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeViewModel.kt
  android/app/src/main/res/layout/fragment_news.xml
Labels: Feat, AN

#201 [BE] 지도 좌표 설정 API 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceGeographyController.java
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceCoordinateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceCoordinateResponse.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceGeographyService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceGeographyControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceCoordinateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceGeographyServiceTest.java
Labels: Feat, BE

#191 [BE] 공지사항 응답 고정, 일반 분리
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementGroupedResponses.java
  backend/src/main/java/com/daedan/festabook/announcement/service/AnnouncementService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/announcement/controller/AnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/service/AnnouncementServiceTest.java
Labels: Refactor, BE

#207 [AN] 소식 > 공지 아이템 표시 기능 추가
  .github/workflows/ci-android.yml
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/NoticeDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/NoticeDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/NoticeListResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/NoticeRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/NoticeService.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/PermissionUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/Toast.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/OnNoticeClickListener.kt
  android/app/src/main/res/drawable/bg_gray100_stroke_gray400_radius_10dp.xml
  android/app/src/main/res/layout/item_notice.xml
Labels: Feat, AN

#204 [AN] 지도 화면 서버 연동
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/OrganizationGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/OrganizationService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/PlaceService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/ApiClient.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/Coordinate.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/OrganizationGeography.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/PlaceGeography.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/PlaceListRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/dummy/DummyPlaceDetail.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/dummy/DummyMapData.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/dummy/DummyPlace.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/CoordinateUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/InitialMapSettingUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCoordinateUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceListUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/res/layout/fragment_place_detail.xml
Labels: Feat, AN

#216 [FE] 공지사항 조회/추가/수정/삭제 API 연결
  frontend/src/components/modals/NoticeModal.jsx
  frontend/src/pages/NoticesPage.jsx
Labels: Feat, FE

#218 [FE] customStyleId 삭제 Hotfix
  frontend/src/components/map/MapSelector.tsx
  frontend/src/pages/MapSettingsPage.jsx
Labels: Fix, FE

#220 [AN] 일정 화면 북마크 제거
  android/app/src/main/res/layout/fragment_schedule.xml
  android/app/src/main/res/layout/fragment_schedule_tab_page.xml
  android/app/src/main/res/layout/item_schedule_tab_page.xml
  android/app/src/main/res/layout/item_schedule_tab_page_skeleton.xml
Labels: Fix, Refactor, AN

#225 [BE] 북마크 = 즐겨찾기 + 알림 분리
  backend/src/main/java/com/daedan/festabook/notification/infrastructure/FcmNotificationManager.java
  backend/src/main/java/com/daedan/festabook/organization/controller/OrganizationNotificationController.java
  backend/src/main/java/com/daedan/festabook/organization/domain/OrganizationNotification.java
  backend/src/main/java/com/daedan/festabook/organization/dto/OrganizationBookmarkResponse.java
  backend/src/main/java/com/daedan/festabook/organization/dto/OrganizationNotificationRequest.java
  backend/src/main/java/com/daedan/festabook/organization/dto/OrganizationNotificationResponse.java
  backend/src/main/java/com/daedan/festabook/organization/infrastructure/OrganizationNotificationJpaRepository.java
  backend/src/main/java/com/daedan/festabook/organization/service/OrganizationNotificationService.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceFavoriteController.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceFavorite.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceNotificationManager.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceBookmarkResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceFavoriteRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceFavoriteResponse.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceFavoriteJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceBookmarkService.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceFavoriteService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/notification/infrastructure/FcmNotificationManagerTest.java
  backend/src/test/java/com/daedan/festabook/organization/controller/OrganizationNotificationControllerTest.java
  backend/src/test/java/com/daedan/festabook/organization/domain/OrganizationBookmarkRequestFixture.java
  backend/src/test/java/com/daedan/festabook/organization/domain/OrganizationNotificationFixture.java
  backend/src/test/java/com/daedan/festabook/organization/dto/OrganizationNotificationRequestFixture.java
  backend/src/test/java/com/daedan/festabook/organization/service/OrganizationNotificationServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceFavoriteControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceBookmarkRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFavoriteFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceFavoriteRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceFavoriteServiceTest.java
Labels: Feat, BE

#214 [BE] 학생회 공지사항 수정 및 삭제 기능 추가
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/announcement/infrastructure/AnnouncementJpaRepository.java
  backend/src/main/java/com/daedan/festabook/announcement/service/AnnouncementService.java
  backend/src/test/java/com/daedan/festabook/announcement/controller/AnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/infrastructure/AnnouncementJpaRepositoryTest.java
  backend/src/test/java/com/daedan/festabook/announcement/service/AnnouncementServiceTest.java
Labels: Feat, BE

#241 [FE] 고정 핀 등록 기능 API 연결
  frontend/src/pages/NoticesPage.jsx
  frontend/src/styles/global.css
Labels: Feat, FE

#253 [FE] 학생회 페이지 플레이스 생성 및 목록 조회 기능 추가
  frontend/src/components/modals/BoothModal.jsx
  frontend/src/pages/BoothsPage.jsx
Labels: Feat, FE

#249 [AN] 지도 초기화가 안되는 버그 해결
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/InitialMapSettingUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapUtil.kt
Labels: Fix, AN

#252 [BE] 고정 Pinned API 추가
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementPinUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/announcement/service/AnnouncementService.java
  backend/src/test/java/com/daedan/festabook/announcement/controller/AnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementPinUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/service/AnnouncementServiceTest.java
Labels: Feat, BE

#258 [FE] 학생회 페이지 플레이스 삭제 API 연동
  frontend/src/pages/BoothsPage.jsx
Labels: Feat, FE

#259 [BE] place 단건 삭제 기능 추가
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceAnnouncementJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceDetailJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceFavoriteJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
Labels: Feat, BE

#256 [AN] 바텀 네비게이션 뷰 디자인 수정
  android/app/src/main/java/com/daedan/festabook/presentation/common/AnimationUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/res/drawable/ic_map.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/menu/menu_bottom_navigation.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#262 [AN] 화면 회전 및 다크모드 테마 막기
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
Labels: Feat, AN

#279 [BE] PlacePreview, PlaceGeography null 처리
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceGeographyResponses.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacePreviewResponse.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceGeographyControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceGeographyServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlacePreviewServiceTest.java
Labels: Fix, BE

#291 [BE] data.sql mysql 문법으로 적용
  backend/src/main/resources/data.sql
Labels: Fix, BE

#284 [AN] uiState 로딩, 실패 처리 및 스켈레톤 UI 구현
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceDetailResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/PlaceResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/BookmarkRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/DeviceRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/NoticeRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceDetailRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/ScheduleRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/util/ApiExtension.kt
  android/app/src/main/java/com/daedan/festabook/data/util/ApiResultException.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/model/PlaceDetailUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/adapter/PlaceListAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceListUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleDatesUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleEventsUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabPageFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleViewModel.kt
  android/app/src/main/res/layout/fragment_news.xml
  android/app/src/main/res/layout/fragment_place_detail.xml
  android/app/src/main/res/layout/fragment_place_detail_skeleton.xml
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/layout/item_notice_skeleton.xml
  android/app/src/main/res/layout/item_place_list.xml
  android/app/src/main/res/layout/item_place_list_skeleton.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN
