Repository woowacourse-teams/2025-festabook, pull requests merged in 2025-09, with the labels that each got.

#665 [BE] dev cd 배포 중 권한 문제 발생 해결
  .github/workflows/backend-cd-dev.yml
Labels: CI/CD, BE

#684 [BE] Question 인가 처리
  backend/src/main/java/com/daedan/festabook/question/controller/QuestionController.java
  backend/src/main/java/com/daedan/festabook/question/domain/Question.java
  backend/src/main/java/com/daedan/festabook/question/service/QuestionService.java
  backend/src/test/java/com/daedan/festabook/question/controller/QuestionControllerTest.java
  backend/src/test/java/com/daedan/festabook/question/domain/QuestionFixture.java
  backend/src/test/java/com/daedan/festabook/question/domain/QuestionTest.java
  backend/src/test/java/com/daedan/festabook/question/service/QuestionServiceTest.java
Labels: Feat, BE

#683 [BE] Lineup 인가 처리
  backend/src/main/java/com/daedan/festabook/lineup/controller/LineupController.java
  backend/src/main/java/com/daedan/festabook/lineup/domain/Lineup.java
  backend/src/main/java/com/daedan/festabook/lineup/service/LineupService.java
  backend/src/test/java/com/daedan/festabook/lineup/controller/LineupControllerTest.java
  backend/src/test/java/com/daedan/festabook/lineup/domain/LineupFixture.java
  backend/src/test/java/com/daedan/festabook/lineup/domain/LineupTest.java
  backend/src/test/java/com/daedan/festabook/lineup/service/LineupServiceTest.java
Labels: Feat, BE

#682 [BE] Festival 인가 처리
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalController.java
  backend/src/main/java/com/daedan/festabook/festival/domain/FestivalImage.java
  backend/src/main/java/com/daedan/festabook/festival/service/FestivalImageService.java
  backend/src/main/java/com/daedan/festabook/festival/service/FestivalService.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalNotificationControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalImageFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalImageTest.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalTest.java
  backend/src/test/java/com/daedan/festabook/festival/service/FestivalImageServiceTest.java
  backend/src/test/java/com/daedan/festabook/festival/service/FestivalNotificationServiceTest.java
  backend/src/test/java/com/daedan/festabook/festival/service/FestivalServiceTest.java
Labels: Feat, BE

#669 [BE] Announcement 인가 처리
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/announcement/service/AnnouncementService.java
  backend/src/test/java/com/daedan/festabook/announcement/controller/AnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementTest.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementPinUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/service/AnnouncementServiceTest.java
Labels: Feat, BE

#695 [BE] Swagger 헤더 안 실리는 문제 해결
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventDateController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalNotificationController.java
  backend/src/main/java/com/daedan/festabook/lineup/controller/LineupController.java
  backend/src/main/java/com/daedan/festabook/lostitem/controller/LostItemController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceFavoriteController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceGeographyController.java
  backend/src/main/java/com/daedan/festabook/question/controller/QuestionController.java
Labels: Fix, BE

#693 [BE] Blue/Green 배포 전략을 위한 CodeBuild, CodeDeploy 설정
  backend/infra/appspec.yml
  backend/infra/buildspec.yml
  backend/infra/deploy.sh
Labels: CI/CD, BE

#707 [FE] dev 서버에 CICD를 실행하는 과정에 권한이 없는 문제 해결
  .github/workflows/frontend-ci-cd-dev.yml
Labels: CI/CD, FE

#716 [FE] 새로운 이미지 추가 안되는 버그
  frontend/src/App.jsx
  frontend/src/components/modals/AddImageModal.jsx
  frontend/src/pages/HomePage.jsx
Labels: Fix, FE

#717 [FE] 새로운 이미지 추가 안되는 버그
  frontend/src/App.jsx
  frontend/src/components/modals/AddImageModal.jsx
  frontend/src/pages/HomePage.jsx
Labels: Fix, FE

#718 [FE] 불필요한 프론트엔드 prod 스크립트 삭제
  .github/workflows/frontend-ci-cd-prod.yml
Labels: Refactor, FE

#702 [BE] Device의 모든 축제 알림 조회 API 구현
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalNotificationController.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalCreateRequest.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalNotificationReadResponse.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalNotificationReadResponses.java
  backend/src/main/java/com/daedan/festabook/festival/infrastructure/FestivalNotificationJpaRepository.java
  backend/src/main/java/com/daedan/festabook/festival/service/FestivalNotificationService.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalNotificationControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/service/FestivalNotificationServiceTest.java
Labels: Feat, BE

#703 [BE] FAQ, Festival 도메인 검증
  backend/src/main/java/com/daedan/festabook/festival/domain/Festival.java
  backend/src/main/java/com/daedan/festabook/question/domain/Question.java
  backend/src/main/resources/db/migration/V2__answer_length.sql
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalTest.java
  backend/src/test/java/com/daedan/festabook/question/domain/QuestionTest.java
Labels: Feat, BE

#721 [BE] @PreAuthorize 어노테이션 추가
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventDateController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalController.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/main/java/com/daedan/festabook/lineup/controller/LineupController.java
  backend/src/main/java/com/daedan/festabook/lostitem/controller/LostItemController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceGeographyController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceImageController.java
  backend/src/main/java/com/daedan/festabook/question/controller/QuestionController.java
  backend/src/main/java/com/daedan/festabook/storage/controller/ImageStoreController.java
Labels: Feat, BE

#727 [BE] Council Update 버그 수정
  backend/src/main/java/com/daedan/festabook/council/service/CouncilService.java
Labels: Fix, BE

#731 [FE] DEV -> PROD 병합
  .github/workflows/frontend-ci-cd-prod.yml
  frontend/src/components/layout/Sidebar.jsx
  frontend/src/components/modals/BoothModal.jsx
Labels: FE, Release

#729 [BE] DEV -> PROD 병합
  .github/workflows/backend-cd-prod.yml
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/council/dto/CouncilResponse.java
  backend/src/main/java/com/daedan/festabook/council/service/CouncilService.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventDateController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalNotificationController.java
  backend/src/main/java/com/daedan/festabook/festival/domain/Festival.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalCreateRequest.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalNotificationReadResponse.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalNotificationReadResponses.java
  backend/src/main/java/com/daedan/festabook/festival/infrastructure/FestivalNotificationJpaRepository.java
  backend/src/main/java/com/daedan/festabook/festival/service/FestivalNotificationService.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/main/java/com/daedan/festabook/lineup/controller/LineupController.java
  backend/src/main/java/com/daedan/festabook/lostitem/controller/LostItemController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceGeographyController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceImageController.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java
  backend/src/main/java/com/daedan/festabook/question/controller/QuestionController.java
  backend/src/main/java/com/daedan/festabook/question/domain/Question.java
  backend/src/main/java/com/daedan/festabook/storage/controller/ImageStoreController.java
  backend/src/main/resources/db/migration/V2__answer_length.sql
  backend/src/test/java/com/daedan/festabook/council/controller/CouncilControllerTest.java
  backend/src/test/java/com/daedan/festabook/council/service/CouncilServiceTest.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalNotificationControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalTest.java
  backend/src/test/java/com/daedan/festabook/festival/service/FestivalNotificationServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
  backend/src/test/java/com/daedan/festabook/question/domain/QuestionTest.java
Labels: BE, Release

#650 [AN] 분실물 추가 시 패딩이 적용 안되는 문제 해결
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemDecoration.kt
Labels: Fix, AN

#655 [AN] 알림 스위치 버튼 연속클릭 제한
  android/app/src/main/java/com/daedan/festabook/presentation/setting/SettingFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/setting/SettingViewModel.kt
Labels: Fix, AN

#744 [BE] DEV -> PROD 병합
  backend/src/main/java/com/daedan/festabook/event/domain/Event.java
  backend/src/main/java/com/daedan/festabook/event/domain/EventDate.java
  backend/src/main/resources/db/migration/V3.0__event_title_varchar_length_modify.sql
  backend/src/main/resources/db/migration/V3.1__event_location_varchar_length_modify.sql
  backend/src/test/java/com/daedan/festabook/event/domain/EventDateFixture.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventDateTest.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventFixture.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventTest.java
Labels: BE, Release

#749 [FE] 프론트엔드 스크립트 트리거 브랜치 변경 및 steps 하나로 변경
  .github/workflows/frontend-ci-cd-dev.yml
Labels: FE

#741 [AN] 일정 화면 로딩 상태 개선
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabPageFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleViewModel.kt
Labels: Fix, AN

#739 [BE] 문자열 길이 도메인 규칙 변경
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/question/domain/Question.java
  backend/src/main/resources/db/migration/V4.0__place_title_varchar_length_modify.sql
  backend/src/main/resources/db/migration/V4.1__question_answer_varchar_length_modify.sql
  backend/src/main/resources/db/migration/V4.2__announcement_content_varchar_length_modify.sql
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceTest.java
  backend/src/test/java/com/daedan/festabook/question/domain/QuestionTest.java
Labels: Feat, BE

#757 [FE] 공지사항 등록 및 알림 전송 기능 분리
  frontend/public/festabook-logo.svg
  frontend/src/App.jsx
  frontend/src/components/modals/NoticeModal.jsx
  frontend/src/components/modals/PushNotificationConfirmModal.jsx
  frontend/src/pages/NoticesPage.jsx
  frontend/src/utils/api.js
Labels: Refactor, FE

#807 [BE] 플레이스 설명 3000자로 변경
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/resources/db/migration/V6__place_description_max_length_modify.sql
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceTest.java
Labels: Feat, BE

#768 [AN] 강제 업데이트 기능 추가
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/AppVersionManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/SplashUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/SplashViewModel.kt
  android/app/src/main/res/layout/view_app_update_alert_dialog.xml
  android/app/src/main/res/layout/view_app_update_failed_alert_dialog.xml
  android/app/src/main/res/layout/view_main_alert_dialog.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: Feat, AN

#811 [BE] 축제 정보 update 로직 수정
  backend/src/main/java/com/daedan/festabook/festival/domain/Festival.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalResponse.java
  backend/src/main/java/com/daedan/festabook/festival/service/FestivalService.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalControllerTest.java
Labels: Fix, BE

#813 [BE] 플레이스 카테고리(포토부스, 기타부스) 추가
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceCategory.java
  backend/src/main/resources/db/migration/V7__place_category_add.sql
Labels: Feat, BE

#818 [FE] DEV -> PROD 병합
  .github/workflows/frontend-ci-cd-dev.yml
  frontend/public/festabook-logo.png
  frontend/public/festabook-logo.svg
  frontend/src/App.jsx
  frontend/src/components/common/Modal.jsx
  frontend/src/components/common/Skeleton.jsx
  frontend/src/components/icons/CategoryIcons.jsx
  frontend/src/components/layout/Sidebar.jsx
  frontend/src/components/map/MapSelector.tsx
  frontend/src/components/modals/AddImageModal.jsx
  frontend/src/components/modals/AnnouncementModal.jsx
  frontend/src/components/modals/BoothModal.jsx
  frontend/src/components/modals/CopyLinkModal.jsx
  frontend/src/components/modals/DatePromptModal.jsx
  frontend/src/components/modals/EventDateModal.jsx
  frontend/src/components/modals/EventModal.jsx
  frontend/src/components/modals/FaqModal.jsx
  frontend/src/components/modals/FestivalImagesModal.jsx
  frontend/src/components/modals/FestivalInfoModal.jsx
  frontend/src/components/modals/LineupAddModal.jsx
  frontend/src/components/modals/LineupEditModal.jsx
  frontend/src/components/modals/LostItemModal.jsx
  frontend/src/components/modals/OtherPlaceEditModal.jsx
  frontend/src/components/modals/PasswordChangeModal.jsx
  frontend/src/components/modals/PlaceAnnouncementModal.jsx
  frontend/src/components/modals/PlaceEditModal.jsx
  frontend/src/components/modals/PlaceImagesModal.jsx
  frontend/src/components/modals/PlaceManageModal.jsx
  frontend/src/components/modals/PlaceModal.jsx
  frontend/src/components/modals/PushNotificationConfirmModal.jsx
  frontend/src/components/modals/ScheduleModal.jsx
  frontend/src/data/categories.js
  frontend/src/index.css
  frontend/src/pages/AnnouncementPage.jsx
  frontend/src/pages/BoothsPage.jsx
  frontend/src/pages/EventPage.jsx
  frontend/src/pages/FaqPage.jsx
  frontend/src/pages/FestivalPage.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/LostFoundPage.jsx
  frontend/src/pages/LostItemPage.jsx
  frontend/src/pages/PlaceGeographyPage.jsx
  frontend/src/pages/PlacePage.jsx
  frontend/src/utils/api.js
Labels: FE, Release

#822 [BE] CloudWatch Agent 사용자 네임스페이스 변경
  backend/src/main/java/com/daedan/festabook/global/config/CloudWatchMetricsConfig.java
Labels: Refactor, BE

#799 [AN] 스낵바 띄울 때 바텀 내비게이션 뷰 떠오르는 문제 해결
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/PermissionUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/res/layout/activity_main.xml
Labels: Feat, AN

#826 [AN] 인앱 업데이트 addOnFailureListener 로직 수정하여 크래시 방지
  android/app/src/main/java/com/daedan/festabook/presentation/splash/AppVersionManager.kt
Labels: Fix, AN

#831 [AN] cd 스크립트 제거
  .github/workflows/android-cd.yml
Labels: CI/CD, AN

#815 [AN] 푸시알림 클릭시 소식화면으로 이동
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/presentation/common/ImageUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/explore/ExploreActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/setting/SettingFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/daedan/festabook/service/MyFirebaseMessagingService.kt
  android/app/src/main/java/com/daedan/festabook/service/NotificationHelper.kt
  android/app/src/main/res/drawable/ic_festabook_logo_notification_large.xml
  android/app/src/main/res/drawable/ic_festabook_logo_notification_small.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#838 [AN] MainActivity 에서 settingViewModel의 saveNotificationId 호출하도록 변경
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalNotificationLocalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalNotificationLocalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/FestivalNotificationRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/setting/SettingFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/setting/SettingViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: Fix, AN

#824 [BE] 분실물 페이지 안내메시지 조회 및 수정 API 구현
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalController.java
  backend/src/main/java/com/daedan/festabook/festival/domain/Festival.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalCreateRequest.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalLostItemGuideResponse.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalLostItemGuideUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalLostItemGuideUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/festival/service/FestivalService.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/main/resources/db/migration/V8__festival_lost_item_add.sql
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalTest.java
  backend/src/test/java/com/daedan/festabook/festival/dto/FestivalCreateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/festival/service/FestivalServiceTest.java
Labels: Feat, BE

#828 [FE] 분실물 습득/수령 가이드 학생회 페이지 추가
  frontend/.gitignore
  frontend/src/App.jsx
  frontend/src/components/modals/LostItemGuideModal.jsx
  frontend/src/contexts/DataProvider.jsx
  frontend/src/data/initialData.js
  frontend/src/pages/LostItemPage.jsx
  frontend/src/utils/api.js
Labels: Feat, FE

#858 [BE] Hot Fix: festival.zoom 필드의 @Column 어노테이션 속성 length 제거
  backend/src/main/java/com/daedan/festabook/festival/domain/Festival.java
Labels: Fix, BE

#862 [FE] gitignore 마지막 줄 개행 추가
  frontend/.gitignore
Labels: FE

#855 [FE] DEV -> PROD 병합
  .github/workflows/frontend-ci-cd-dev.yml
  frontend/.gitignore
  frontend/src/App.jsx
  frontend/src/components/modals/LostItemGuideModal.jsx
  frontend/src/contexts/DataProvider.jsx
  frontend/src/data/initialData.js
  frontend/src/pages/LostItemPage.jsx
  frontend/src/utils/api.js
Labels: Feat, FE, Release

#820 [BE] 기타 플레이스 제목 수정 API 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/place/dto/EtcPlaceUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/EtcPlaceUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/MainPlaceUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/MainPlaceUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/dto/EtcPlaceUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/MainPlaceUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
Labels: Feat, BE

#876 [BE] Device Update API 구현
  backend/src/main/java/com/daedan/festabook/device/controller/DeviceController.java
  backend/src/main/java/com/daedan/festabook/device/domain/Device.java
  backend/src/main/java/com/daedan/festabook/device/dto/DeviceUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/device/service/DeviceService.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/test/java/com/daedan/festabook/device/controller/DeviceControllerTest.java
  backend/src/test/java/com/daedan/festabook/device/dto/DeviceUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/device/service/DeviceServiceTest.java
Labels: Feat, BE

#877 [BE] DEV -> PROD 병합
  backend/src/main/java/com/daedan/festabook/device/controller/DeviceController.java
  backend/src/main/java/com/daedan/festabook/device/domain/Device.java
  backend/src/main/java/com/daedan/festabook/device/dto/DeviceUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/device/service/DeviceService.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/test/java/com/daedan/festabook/device/controller/DeviceControllerTest.java
  backend/src/test/java/com/daedan/festabook/device/dto/DeviceUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/device/service/DeviceServiceTest.java
Labels: BE, Release

#863 [BE] FCM 알림 구독 PREFIX 주입 방식 변경
  backend/src/main/java/com/daedan/festabook/notification/infrastructure/FcmNotificationManager.java
  backend/src/test/resources/application.yml
Labels: Refactor, BE

#883 [BE] FCM 알림 구독 iOS 대응
  backend/src/main/java/com/daedan/festabook/festival/controller/AndroidFestivalNotificationSubscriptionController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalNotificationSubscriptionController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/IosFestivalNotificationSubscriptionController.java
  backend/src/main/java/com/daedan/festabook/festival/domain/FestivalNotificationManager.java
  backend/src/main/java/com/daedan/festabook/festival/service/FestivalNotificationService.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/main/java/com/daedan/festabook/notification/infrastructure/FcmNotificationManager.java
  backend/src/test/java/com/daedan/festabook/festival/controller/AndroidFestivalNotificationSubscriptionControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalNotificationSubscriptionControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/controller/IosFestivalNotificationSubscriptionControllerTest.java
  backend/src/test/resources/application.yml
Labels: Feat, BE

#864 [BE] 토큰 권한 검증을 데이터베이스가 아닌, token 값 기반으로 변경
  backend/src/main/java/com/daedan/festabook/council/controller/CouncilController.java
  backend/src/main/java/com/daedan/festabook/council/domain/Council.java
  backend/src/main/java/com/daedan/festabook/council/service/CouncilService.java
  backend/src/main/java/com/daedan/festabook/global/security/council/CouncilDetails.java
  backend/src/main/java/com/daedan/festabook/global/security/council/CouncilDetailsService.java
  backend/src/main/java/com/daedan/festabook/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/daedan/festabook/global/security/util/JwtProvider.java
  backend/src/test/java/com/daedan/festabook/council/service/CouncilServiceTest.java
  backend/src/test/java/com/daedan/festabook/global/security/JwtTestHelper.java
  backend/src/test/java/com/daedan/festabook/global/security/util/JwtProviderTest.java
Labels: Feat, BE

#880 [BE] @PreAuthorize에 Admin 권한 추가
  backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java
  backend/src/main/java/com/daedan/festabook/council/controller/CouncilController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventDateController.java
  backend/src/main/java/com/daedan/festabook/festival/controller/FestivalController.java
  backend/src/main/java/com/daedan/festabook/lineup/controller/LineupController.java
  backend/src/main/java/com/daedan/festabook/lostitem/controller/LostItemController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceGeographyController.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceImageController.java
  backend/src/main/java/com/daedan/festabook/question/controller/QuestionController.java
  backend/src/main/java/com/daedan/festabook/storage/controller/ImageStoreController.java
  backend/src/test/java/com/daedan/festabook/announcement/controller/AnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/council/controller/CouncilControllerTest.java
  backend/src/test/java/com/daedan/festabook/event/controller/EventControllerTest.java
  backend/src/test/java/com/daedan/festabook/event/controller/EventDateControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/dto/FestivalCreateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/global/security/JwtTestHelper.java
  backend/src/test/java/com/daedan/festabook/lineup/controller/LineupControllerTest.java
  backend/src/test/java/com/daedan/festabook/lostitem/controller/LostItemControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceGeographyControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceImageControllerTest.java
  backend/src/test/java/com/daedan/festabook/question/controller/QuestionControllerTest.java
  backend/src/test/java/com/daedan/festabook/storage/controller/ImageStoreControllerTest.java
Labels: Feat, BE

#887 [BE] 노출되면 안되는 값을 로그에서 마스킹
  backend/src/main/java/com/daedan/festabook/global/logging/LocalLoggingFilter.java
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingFilter.java
  backend/src/main/java/com/daedan/festabook/global/logging/MaskingPath.java
  backend/src/test/java/com/daedan/festabook/global/security/JwtTestHelper.java
Labels: Feat, BE

#890 [BE] @PreAuthorize의 인증/인가 예외를 GlobalExceptionHandler에서 처리
  backend/src/main/java/com/daedan/festabook/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/daedan/festabook/global/logging/dto/ExceptionLog.java
Labels: Feat, BE

#902 [BE] hotfix: 응답 status code 수정
  backend/src/test/java/com/daedan/festabook/council/controller/CouncilControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalControllerTest.java
Labels: Fix, BE

#907 [BE] DEV -> PROD 병합
  backend/build.gradle
  backend/src/main/java/com/daedan/festabook/global/logging/LocalLoggingAspect.java
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingAspect.java
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingFilter.java
Labels: Feat, BE

#905 [AN] 아이템이 없을 시 문구 표시
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/FAQFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabPageFragment.kt
  android/app/src/main/res/layout/fragment_faq.xml
  android/app/src/main/res/layout/fragment_lost_item.xml
  android/app/src/main/res/layout/fragment_notice.xml
  android/app/src/main/res/layout/fragment_schedule_tab_page.xml
  android/app/src/main/res/layout/item_empty_state.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#916 [AN] v 1.1.0 업데이트
  android/app/build.gradle.kts
Labels: AN, Minor

#904 [BE] ci 트리거 branch backend-dev/prod로 변경
  .github/workflows/backend-ci.yml
Labels: Fix, BE

#911 [BE] 외부 의존성 로그 기록 추가
  backend/src/main/java/com/daedan/festabook/global/logging/LocalLoggingAspect.java
  backend/src/main/java/com/daedan/festabook/global/logging/Loggable.java
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingAspect.java
  backend/src/main/java/com/daedan/festabook/notification/infrastructure/FcmNotificationManager.java
  backend/src/main/java/com/daedan/festabook/storage/infrastructure/LocalStorageManager.java
  backend/src/main/java/com/daedan/festabook/storage/infrastructure/MockStorageManager.java
  backend/src/main/java/com/daedan/festabook/storage/infrastructure/S3StorageManager.java
Labels: Feat, BE

#922 [AN] Release v 1.1.1
  android/app/build.gradle.kts
Labels: AN, Release

#929 [BE] CodePipeline CI/CD 최적화
  backend/infra/appspec.yml
  backend/infra/buildspec.yml
  backend/infra/deploy.sh
  backend/infra/start.sh
Labels: Refactor, BE

#927 [BE] 시간 태그 기능 추가
  backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/dto/MainPlaceUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/MainPlaceUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceCreateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceCreateResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacePreviewResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacePreviewResponses.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponse.java
  backend/src/main/java/com/daedan/festabook/place/service/PlacePreviewService.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceService.java
  backend/src/main/java/com/daedan/festabook/timetag/controller/TimeTagController.java
  backend/src/main/java/com/daedan/festabook/timetag/domain/PlaceTimeTag.java
  backend/src/main/java/com/daedan/festabook/timetag/domain/TimeTag.java
  backend/src/main/java/com/daedan/festabook/timetag/dto/TimeTagCreateRequest.java
  backend/src/main/java/com/daedan/festabook/timetag/dto/TimeTagCreateResponse.java
  backend/src/main/java/com/daedan/festabook/timetag/dto/TimeTagResponse.java
  backend/src/main/java/com/daedan/festabook/timetag/dto/TimeTagResponses.java
  backend/src/main/java/com/daedan/festabook/timetag/dto/TimeTagUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/timetag/dto/TimeTagUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/timetag/infrastructure/PlaceTimeTagJpaRepository.java
  backend/src/main/java/com/daedan/festabook/timetag/infrastructure/TimeTagJpaRepository.java
  backend/src/main/java/com/daedan/festabook/timetag/service/TimeTagService.java
  backend/src/main/resources/db/migration/V10.0__create_time_tag.sql
  backend/src/main/resources/db/migration/V10.1__create_place_time_tag.sql
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/dto/MainPlaceUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceCreateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlacePreviewServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
  backend/src/test/java/com/daedan/festabook/timetag/controller/TimeTagControllerTest.java
  backend/src/test/java/com/daedan/festabook/timetag/domain/PlaceTimeTagFixture.java
  backend/src/test/java/com/daedan/festabook/timetag/domain/TimeTagFixture.java
  backend/src/test/java/com/daedan/festabook/timetag/domain/TimeTagTest.java
  backend/src/test/java/com/daedan/festabook/timetag/dto/TimeTagCreateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/timetag/dto/TimeTagUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/timetag/service/TimeTagServiceTest.java
Labels: Feat, BE

#928 [FE] 시간 태그 필터링 기능 추가
  frontend/src/App.jsx
  frontend/src/components/modals/PlaceEditModal.jsx
  frontend/src/components/modals/TimeTagAddModal.jsx
  frontend/src/components/modals/TimeTagEditModal.jsx
  frontend/src/pages/PlaceGeographyPage.jsx
  frontend/src/pages/PlacePage.jsx
  frontend/src/utils/api.js
Labels: Feat, FE

#943 [FE] 플레이스 추가 버튼을 각 카테고리에서 할 수 있게 추가
  frontend/src/pages/PlacePage.jsx
Labels: Feat, FE

#947 [FE] 운영 주체도 검색 범위에 포함
  frontend/src/pages/PlacePage.jsx
Labels: Feat, FE

#949 [FE] 좌표 수정할 때 festival 중앙이 아닌 마커를 중앙으로 설정
  frontend/src/components/map/MapSelector.tsx
Labels: Feat, FE

#976 [AN] 지도 화면에서 타임 태그 필터 적용 및 구현
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceDetailResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/TimeTagResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/PlaceService.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/Place.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/PlaceGeography.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/TimeTag.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/PlaceListRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListChildViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCoordinateUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceListUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/PlaceMapFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/timeTagSpinner/adapter/TimeTagSpinnerAdapter.kt
  android/app/src/main/res/drawable/bg_spinner_dropdown.xml
  android/app/src/main/res/drawable/ic_arrow_down.xml
  android/app/src/main/res/drawable/sel_time_tag.xml
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/layout/fragment_place_map.xml
  android/app/src/main/res/layout/item_spinner_dropdown.xml
  android/app/src/main/res/layout/item_spinner_selected.xml
  android/app/src/test/java/com/daedan/festabook/placeList/PlaceListChildViewModelTest.kt
Labels: Feat, AN

#985 [BE] 플레이스 일괄 복제 API 추가
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacesCloneRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacesCloneResponse.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlacesCloneRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
Labels: Feat, BE

#991 [AN] Hotfix: 전역 예외 처리기 개선 및 크래시리틱스 적용
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/error/ErrorActivity.kt
  android/app/src/main/java/com/daedan/festabook/util/FestabookGlobalExceptionHandler.kt
  android/app/src/main/res/drawable/ic_uncaught_error.xml
  android/app/src/main/res/layout/activity_error.xml
  android/app/src/main/res/values/strings.xml
Labels: Fix, AN

#995 [AN] 포스터 이미지, 상세 이미지 확대 기능 추가
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/presentation/common/ImageUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/PosterItemViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/adapter/PlaceImageViewPagerAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/adapter/PlaceImageViewPagerViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/gradle/libs.versions.toml
Labels: Feat, AN

#1007 [AN] 지도, 플레이스 화면 로깅 추가
  android/app/proguard-rules.pro
  android/app/src/main/java/com/daedan/festabook/logging/DefaultFirebaseLogger.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/logging/PlaceDetailImageClick.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/logging/PlaceDetailImageSwipe.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/behavior/PlaceListBottomSheetBehavior.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/LocationPermissionChanged.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceBackToSchoolClick.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceCategoryClick.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceFragmentEnter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceItemClick.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceListSwipeUp.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceMapButtonReClick.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceMarkerClick.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlacePreviewClick.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/logging/PlaceTimeTagSelected.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeCategory/PlaceCategoryFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewSecondaryFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/PlaceMapFragment.kt
Labels: Chore, AN
