Repository woowacourse-teams/2025-festabook, pull requests merged in 2025-08, with the labels that each got.

#302 [BE] 모킹 데이터 변경
  backend/src/main/resources/data.sql
Labels: Chore, BE

#299 [FE] 백엔드 서버 엔드포인트 연결
  frontend/src/components/modals/ScheduleModal.jsx
  frontend/src/contexts/DataProvider.jsx
  frontend/src/pages/SchedulePage.jsx
  frontend/src/styles/global.css
  frontend/src/utils/api.js
Labels: Feat, FE

#308 [BE] 모킹 데이터 추가
  backend/src/main/resources/data.sql
Labels: Chore, BE

#304 [BE] PlaceDetail 검증 로직 추가
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceDetail.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceDetailFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceDetailTest.java
Labels: Feat, BE

#314 [FE] Q&A 페이지 구현
  frontend/src/components/common/ConfirmModal.jsx
  frontend/src/components/modals/QnaModal.jsx
  frontend/src/contexts/DataProvider.jsx
  frontend/src/data/initialData.js
  frontend/src/pages/QnaPage.jsx
  frontend/src/utils/api.js
Labels: Feat, FE

#301 [AN] 홈 화면 서버 연결
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/OrganizationDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/OrganizationDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/OrganizationResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/FestivalRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/OrganizationService.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/Festival.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/Organization.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/Poster.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/FestivalRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/TextUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/CenterItemMotionEnlarger.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/FestivalUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/PosterAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/PosterItemViewHolder.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_home_poster.xml
  android/app/src/main/res/values/dimens.xml
Labels: Fix, Feat, AN

#310 [BE] OrganizationResponse 시작일, 종료일을 연관된 EventDate로 변경
  backend/src/main/java/com/daedan/festabook/event/infrastructure/EventDateJpaRepository.java
  backend/src/main/java/com/daedan/festabook/organization/domain/Organization.java
  backend/src/main/java/com/daedan/festabook/organization/dto/OrganizationResponse.java
  backend/src/main/java/com/daedan/festabook/organization/service/OrganizationService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/organization/controller/OrganizationControllerTest.java
  backend/src/test/java/com/daedan/festabook/organization/domain/OrganizationFixture.java
  backend/src/test/java/com/daedan/festabook/organization/service/OrganizationServiceTest.java
Labels: Feat, BE

#332 [FE] 학생회 홈 페이지 구현
  frontend/src/App.jsx
  frontend/src/components/modals/AddImageModal.jsx
  frontend/src/components/modals/FestivalImagesModal.jsx
  frontend/src/components/modals/FestivalInfoModal.jsx
  frontend/src/pages/GenericPage.jsx
  frontend/src/pages/HomePage.jsx
Labels: Feat, FE

#335 [BE] Organization 시작일, 종료일 EventDate와 분리
  backend/src/main/java/com/daedan/festabook/event/infrastructure/EventDateJpaRepository.java
  backend/src/main/java/com/daedan/festabook/organization/domain/Organization.java
  backend/src/main/java/com/daedan/festabook/organization/dto/OrganizationResponse.java
  backend/src/main/java/com/daedan/festabook/organization/service/OrganizationService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/organization/controller/OrganizationControllerTest.java
  backend/src/test/java/com/daedan/festabook/organization/domain/OrganizationFixture.java
  backend/src/test/java/com/daedan/festabook/organization/service/OrganizationServiceTest.java
Labels: Refactor, BE

#330 [COMMON] 버저닝 자동화 GitHub Actions Workflow 생성
  .github/template/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Common, Release

#343 [COMMON] 코드 레빗 충돌 수정
  .coderabbit.yaml
Labels: Fix, Common

#347 [AN] Q&A 화면 구현
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/NoticeDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/device/DeviceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/device/DeviceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/notice/NoticeDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/notice/NoticeDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/OrganizationBookmarkDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/OrganizationBookmarkDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/schedule/ScheduleDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/schedule/ScheduleDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/notice/NoticeListResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/notice/NoticeResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/organization/OrganizationBookmarkResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/organization/OrganizationGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceDetailResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/schedule/ScheduleDateResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/schedule/ScheduleEventResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/BookmarkRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/DeviceRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/NoticeRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceDetailRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/ScheduleRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/NoticeService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/OrganizationBookmarkService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/OrganizationService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/PlaceService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/ScheduleService.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/adapter/NewsPagerAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/FAGFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/FAQFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/adapter/FAQAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/adapter/FAQViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/model/FAQItemUiModel.kt
  android/app/src/main/res/drawable/bg_gray100_stroke_gray200_radius_16dp.xml
  android/app/src/main/res/drawable/ic_chevron_down.xml
  android/app/src/main/res/drawable/ic_chevron_up.xml
  android/app/src/main/res/layout/fragment_f_a_q.xml
  android/app/src/main/res/layout/item_faq.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: Feat, AN

#348 [AN] Q&A 화면 구현
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/faq/FAQDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/faq/FAQDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/FAQResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/FAQRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/FAQService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/ApiClient.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/FAQItem.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/FAQRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/FAQFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/FAQUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/adapter/FAQAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/adapter/FAQViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/model/FAQItemUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/OnNewsClickListener.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/adapter/PlaceNoticeViewHolder.kt
  android/app/src/main/res/layout/fragment_f_a_q.xml
  android/app/src/main/res/layout/fragment_notice.xml
  android/app/src/main/res/layout/item_faq.xml
  android/app/src/main/res/layout/item_notice.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#322 [AN] BottomNavigationView 중앙 맞지 않는 버그 해결
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
Labels: Fix, AN

#325 [AN] 플레이스 textview end-end 제약 조건 추가
  android/app/src/main/res/layout/fragment_place_detail.xml
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/layout/item_place_list.xml
  android/app/src/main/res/layout/item_place_list_header.xml
Labels: Fix, Refactor, AN

#334 [BE] Swagger 정렬 순서 변경
  backend/src/main/resources/application.yml
Labels: Refactor, BE

#346 [BE, CICD] 개발 서버 RDB의 JPA-DDL create-drop 동작 중 테이블 삭제 실패 문제 해결
  .github/workflows/ci-cd-backend.yml
  backend/src/main/resources/application.yml
Labels: CI/CD, BE

#363 [BE, CI/CD] 스크립트 최적화 및 old jar 파일 삭제 로직 개선
  .github/workflows/backend-cd-fuyu-server.yml
  .github/workflows/backend-ci-pr-gradle-test.yml
Labels: CI/CD, BE

#365 [AN, CI/CD] android ci Gradle 캐싱 처리
  .github/workflows/android-ci-pr-test.yml
Labels: CI/CD, AN

#317 [BE, CICD] 백엔드 EC2 깃허브 액션 배포 스크립트 작성
  .github/workflows/backend-cd-ec2.yml
Labels: CI/CD, BE

#356 [AN] firebase 외부 모니터링 도구 연동
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: AN, Build

#377 [BE] 분실물 추가/조회 API 생성 (Cherry 이후)
  backend/src/main/java/com/daedan/festabook/lostitem/controller/LostItemController.java
  backend/src/main/java/com/daedan/festabook/lostitem/domain/LostItem.java
  backend/src/main/java/com/daedan/festabook/lostitem/dto/LostItemRequest.java
  backend/src/main/java/com/daedan/festabook/lostitem/dto/LostItemResponse.java
  backend/src/main/java/com/daedan/festabook/lostitem/dto/LostItemResponses.java
  backend/src/main/java/com/daedan/festabook/lostitem/infrastructure/LostItemJpaRepository.java
  backend/src/main/java/com/daedan/festabook/lostitem/service/LostItemService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/lostitem/controller/LostItemControllerTest.java
  backend/src/test/java/com/daedan/festabook/lostitem/domain/LostItemFixture.java
  backend/src/test/java/com/daedan/festabook/lostitem/domain/LostItemTest.java
  backend/src/test/java/com/daedan/festabook/lostitem/dto/LostItemRequestFixture.java
  backend/src/test/java/com/daedan/festabook/lostitem/service/LostItemServiceTest.java
Labels: Feat, BE

#389 [BE, CICD] EC2 깃허브 액션 스크립트 Spring WAS 종료 문제 수정 (jdk 작업 제거, 사용자 권한 sudo 사용)
  .github/workflows/backend-cd-ec2.yml
Labels: CI/CD, BE

#400 [AN] organization -> festival api 변경에 따른 네트워크 통신 구조 변경
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/FestivalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/FestivalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/OrganizationDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/FestivalRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/FestivalService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/ApiClient.kt
  android/app/src/main/res/layout/fragment_place_list.xml
Labels: Feat, AN

#398 [COMMON] GitHub Noti 커스터마이징
  .github/workflows/slack-notify.yml
Labels: Feat, Common

#362 [AN] 분실물 화면 구현
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/LostItemRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/LostItem.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/LostItemRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemDecoration.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemModalDialogFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/adapter/LostItemAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/adapter/LostItemViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/model/LostItemUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/OnNewsClickListener.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailActivity.kt
  android/app/src/main/res/drawable/bg_gray050_radius_10dp.xml
  android/app/src/main/res/layout/fragment_lost_item.xml
  android/app/src/main/res/layout/fragment_lost_item_modal_dialog.xml
  android/app/src/main/res/layout/fragment_news.xml
  android/app/src/main/res/layout/item_lost.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: Feat, AN

#369 [AN] 바텀 네비게이션 지도 버튼 누르면 바텀시트가 내려가고 지도가 보이게 변경
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
Labels: Feat, AN

#406 [AN] Organization -> Festival api 변경에 따른 홈 화면 서버 통신 로직 변경
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/FestivalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/FestivalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/festival/OrganizationResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/FestivalRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/FestivalService.kt
Labels: Refactor, AN

#403 [COMMON] GitHub Noti 커스터마이징
  .github/workflows/slack-notify.yml
Labels: Feat, Common

#383 [AN] viewModel 테스트 작성
  android/app/build.gradle.kts
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleViewModel.kt
  android/app/src/test/java/com/daedan/festabook/home/HomeTestFixture.kt
  android/app/src/test/java/com/daedan/festabook/home/HomeViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/main/MainTestFixture.kt
  android/app/src/test/java/com/daedan/festabook/main/MainViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/news/NewsTestFixture.kt
  android/app/src/test/java/com/daedan/festabook/news/NewsViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/placeDetail/PlaceDetailTestFixture.kt
  android/app/src/test/java/com/daedan/festabook/placeDetail/PlaceDetailViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/placeList/PlaceLIstTestFixture.kt
  android/app/src/test/java/com/daedan/festabook/placeList/PlaceListViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/schedule/ScheduleTestFixtures.kt
  android/app/src/test/java/com/daedan/festabook/schedule/ScheduleViewModelTest.kt
  android/gradle/libs.versions.toml
Labels: AN, Test

#404 [AN] 지도 마커 클릭 시 상세 정보 바텀 시트 구현
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/model/NoticeUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/model/ImageUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/model/PlaceDetailUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListBottomSheetCallback.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCategoryUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCoordinateUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapClickListener.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/res/layout/activity_place_detail.xml
  android/app/src/main/res/layout/fragment_lost_item.xml
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/values/themes.xml
Labels: Feat, AN

#411 [AN] 설정 화면에 서비스 이용약관 및 문의하기 기능 추가
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/setting/SettingFragment.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/daedan/festabook/news/NewsTestFixture.kt
  android/app/src/test/java/com/daedan/festabook/news/NewsViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/placeDetail/PlaceDetailViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/placeList/PlaceListViewModelTest.kt
Labels: Feat, AN

#409 [AN] PlaceDetailActivity 접근 로직 수정
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/adapter/PlaceListViewHolder.kt
  android/app/src/main/res/layout/item_place_list.xml
Labels: Fix, AN

#401 [AN] fragment 동작 firebase analytics 연결
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/logging/FirebaseAnalyticsTree.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/BaseFragment.kt
Labels: Feat, AN

#417 [AN] 일정 , 소식화면 디자인 변경
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/FAQFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/adapter/FAQAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/adapter/FAQViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/adapter/NoticeViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/adapter/ScheduleItemViewHolder.kt
  android/app/src/main/res/drawable/bg_stroke_gray200_radius_16dp.xml
  android/app/src/main/res/layout/fragment_f_a_q.xml
  android/app/src/main/res/layout/fragment_notice.xml
  android/app/src/main/res/layout/item_notice.xml
  android/app/src/main/res/layout/item_notice_skeleton.xml
Labels: Fix, AN

#414 [AN] 로깅 Crashlytics 추가
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/ApiResult.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/faq/FAQFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/notice/NoticeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabPageFragment.kt
  android/app/src/main/java/com/daedan/festabook/util/CrashlyticsTree.kt
  android/app/src/main/java/com/daedan/festabook/util/FestabookGlobalExceptionHandler.kt
  android/app/src/main/res/layout/fragment_place_list.xml
Labels: Feat, AN

#412 [BE] 로그 추가 및 로그 파일 appender cd 로직에 추가
  .github/workflows/backend-cd-ec2.yml
  backend/.gitignore
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingAspect.java
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingFilter.java
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/daedan/festabook/global/exception/GlobalExceptionHandlerTest.java
Labels: Feat, CI/CD, BE

#425 [BE] DTO 변수명 구체적으로 변경
  backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementResponse.java
  backend/src/main/java/com/daedan/festabook/device/dto/DeviceResponse.java
  backend/src/main/java/com/daedan/festabook/event/domain/Event.java
  backend/src/main/java/com/daedan/festabook/event/dto/EventDateResponse.java
  backend/src/main/java/com/daedan/festabook/event/dto/EventRequest.java
  backend/src/main/java/com/daedan/festabook/event/dto/EventResponse.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalNotificationResponse.java
  backend/src/main/java/com/daedan/festabook/festival/dto/FestivalResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceCoordinateResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceFavoriteResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceGeographyResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlacePreviewResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponse.java
  backend/src/test/java/com/daedan/festabook/announcement/controller/AnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/device/controller/DeviceControllerTest.java
  backend/src/test/java/com/daedan/festabook/device/domain/DeviceFixture.java
  backend/src/test/java/com/daedan/festabook/device/domain/DeviceTest.java
  backend/src/test/java/com/daedan/festabook/device/service/DeviceServiceTest.java
  backend/src/test/java/com/daedan/festabook/event/controller/EventControllerTest.java
  backend/src/test/java/com/daedan/festabook/event/controller/EventDateControllerTest.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventFixture.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventTest.java
  backend/src/test/java/com/daedan/festabook/event/dto/EventRequestFixture.java
  backend/src/test/java/com/daedan/festabook/event/service/EventDateServiceTest.java
  backend/src/test/java/com/daedan/festabook/event/service/EventServiceTest.java
  backend/src/test/java/com/daedan/festabook/festival/controller/FestivalNotificationControllerTest.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalImageFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalNotificationFixture.java
  backend/src/test/java/com/daedan/festabook/festival/service/FestivalNotificationServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceFavoriteControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceGeographyControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFavoriteFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceFavoriteServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceGeographyServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
  backend/src/test/java/com/daedan/festabook/question/domain/QuestionFixture.java
  backend/src/test/java/com/daedan/festabook/question/dto/QuestionSequenceUpdateRequestFixture.java
Labels: Refactor, BE

#435 [FE] 변경된 API 반영
  frontend/src/components/layout/Sidebar.jsx
  frontend/src/components/map/MapSelector.tsx
  frontend/src/components/modals/AddImageModal.jsx
  frontend/src/components/modals/BoothModal.jsx
  frontend/src/components/modals/FestivalImagesModal.jsx
  frontend/src/components/modals/FestivalInfoModal.jsx
  frontend/src/components/modals/ScheduleModal.jsx
  frontend/src/contexts/DataProvider.jsx
  frontend/src/pages/BoothsPage.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/MapSettingsPage.jsx
  frontend/src/pages/NoticesPage.jsx
  frontend/src/pages/OrganizationPage.jsx
  frontend/src/pages/SchedulePage.jsx
  frontend/src/styles/global.css
  frontend/src/utils/api.js
Labels: Refactor, FE

#436 [COMMON] GItHub Slack Noti 개선
  .github/workflows/common-slack-notify-opened.yml
  .github/workflows/common-slack-notify-rerequested.yml
  .github/workflows/common-slack-notify-submitted.yml
  .github/workflows/slack-notify.yml
Labels: Refactor, Common

#443 [AN] DTO id명 변경
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/FestivalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/FestivalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/OrganizationBookmarkDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/organization/OrganizationBookmarkDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/place/PlaceDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/request/FestivalNotificationRequest.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/DeviceRegisterResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/festival/FestivalGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/festival/FestivalNotificationResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/festival/FestivalResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/notice/NoticeResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/organization/OrganizationBookmarkResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceDetailResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceGeographyResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/place/PlaceResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/schedule/ScheduleDateResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/schedule/ScheduleEventResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/BookmarkRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/PlaceListRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/FestivalService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/OrganizationBookmarkService.kt
Labels: Fix, AN

#430 [BE] 분실물 상태 수정 API 설계 및 사진 Mock 데이터 변경
  backend/src/main/java/com/daedan/festabook/lostitem/controller/LostItemController.java
  backend/src/main/java/com/daedan/festabook/lostitem/domain/LostItem.java
  backend/src/main/java/com/daedan/festabook/lostitem/dto/LostItemResponse.java
  backend/src/main/java/com/daedan/festabook/lostitem/dto/LostItemStatusUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/lostitem/dto/LostItemStatusUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/lostitem/service/LostItemService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/lostitem/controller/LostItemControllerTest.java
  backend/src/test/java/com/daedan/festabook/lostitem/domain/LostItemFixture.java
  backend/src/test/java/com/daedan/festabook/lostitem/dto/LostItemStatusUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/lostitem/service/LostItemServiceTest.java
Labels: Feat, BE

#432 [FE] 분실물 학생회 페이지 수정 및 API 연결
  frontend/src/contexts/DataProvider.jsx
  frontend/src/pages/LostFoundPage.jsx
  frontend/src/utils/api.js
Labels: Feat, FE

#454 [BE] 우리 패키지 내에 있는 클래스 빈들만 포함하도록 포인트컷 수정
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingAspect.java
Labels: Feat, BE

#469 [BE] 톰켓 메트릭 수집 허용
  backend/src/main/resources/application.yml
Labels: Feat, BE

#457 [BE] 출력하는 로그 정보를 수정
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingAspect.java
  backend/src/main/java/com/daedan/festabook/global/logging/LoggingFilter.java
  backend/src/main/java/com/daedan/festabook/global/logging/RequestBodyCachingFilter.java
  backend/src/main/resources/logback-spring.xml
Labels: Feat, BE

#473 [BE] 플레이스 이미지 생성 api 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceImageController.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageRequest.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceImageService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceImageControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceImageRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceImageServiceTest.java
Labels: Feat, BE

#474 [BE] 플레이스 이미지 삭제 api 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceImageController.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceImageService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceImageControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceImageServiceTest.java
Labels: Feat, BE

#465 [AN] PlaceListFragment 분리
  android/app/src/main/java/com/daedan/festabook/presentation/common/FragmentUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListChildViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/behavior/MoveToInitialPositionCallback.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/behavior/PlaceListBottomSheetBehavior.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/SelectedPlaceUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeCategory/PlaceCategoryFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapClickListenerImpl.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/PlaceMapFragment.kt
  android/app/src/main/res/layout/fragment_place_category.xml
  android/app/src/main/res/layout/fragment_place_detail_preview.xml
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/layout/fragment_place_map.xml
  android/app/src/test/java/com/daedan/festabook/placeList/PlaceListChildViewModelTest.kt
  android/app/src/test/java/com/daedan/festabook/placeList/PlaceListViewModelTest.kt
Labels: Refactor, AN

#492 [FE] Frontend 스크립트 변경
  .github/workflows/ci-cd-frontend.yml
  .github/workflows/frontend-ci-cd-dev.yml
  .github/workflows/frontend-ci-cd-prod.yml
  frontend/src/utils/api.js
Labels: CI/CD, FE

#472 [BE] 일정 post, update API의 Request, Response DTO 추가
  backend/src/main/java/com/daedan/festabook/event/controller/EventController.java
  backend/src/main/java/com/daedan/festabook/event/controller/EventDateController.java
  backend/src/main/java/com/daedan/festabook/event/dto/EventDateUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/event/dto/EventDateUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/event/dto/EventUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/event/dto/EventUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/event/service/EventDateService.java
  backend/src/main/java/com/daedan/festabook/event/service/EventService.java
  backend/src/test/java/com/daedan/festabook/event/controller/EventControllerTest.java
  backend/src/test/java/com/daedan/festabook/event/controller/EventDateControllerTest.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventDateFixture.java
  backend/src/test/java/com/daedan/festabook/event/dto/EventDateUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/event/dto/EventUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/event/service/EventDateServiceTest.java
  backend/src/test/java/com/daedan/festabook/event/service/EventServiceTest.java
Labels: Refactor, BE

#503 [BE] h2 testRuntimeOnly
  backend/build.gradle
Labels: Chore, BE

#506 [FE] 프론트 스크립트 실행 테스트
  .github/workflows/frontend-ci-cd-dev.yml
  .github/workflows/frontend-ci-cd-prod.yml
Labels: CI/CD, FE

#441 [AN] 분실물 화면 새로고침 기능 추가
  android/app/src/main/java/com/daedan/festabook/presentation/news/NewsViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemDecoration.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/LostItemUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/adapter/LostItemViewHolder.kt
  android/app/src/main/res/drawable/bg_skeleton_radius_10dp.xml
  android/app/src/main/res/drawable/bg_skeleton_radius_16dp.xml
  android/app/src/main/res/drawable/bg_skeleton_radius_20dp.xml
  android/app/src/main/res/layout/fragment_lost_item.xml
  android/app/src/main/res/layout/item_lost_skeleton.xml
  android/app/src/main/res/layout/item_notice_skeleton.xml
  android/app/src/main/res/layout/item_place_list_skeleton.xml
  android/app/src/main/res/layout/item_schedule_tab_page_skeleton.xml
  android/app/src/main/res/layout/item_schedule_tab_skeleton.xml
Labels: Feat, AN

#479 [BE] 플레이스 공지 생성 api 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementRequest.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceAnnouncementJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceAnnouncementRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
Labels: Feat, BE

#480 [BE] 플레이스 공지 삭제 api 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
Labels: Feat, BE

#481 [BE] 플레이스 공지사항 수정 api 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementTest.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
Labels: Feat, BE

#485 [BE] 플레이스 이미지 생성(추가), 순서 변경, 삭제 api 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceImageController.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageSequenceUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageSequenceUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageSequenceUpdateResponses.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceImageService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceImageControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceImageRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceImageSequenceUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceImageServiceTest.java
Labels: Feat, BE

#467 [BE] place 생성 시 title을 포함해서 생성으로 변경 및 카테고리 추가
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceCategory.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponse.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceTest.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlacePreviewServiceTest.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
Labels: Feat, BE

#511 [AN] Release 버전 빌드가 안되는 문제 해결
  .github/workflows/android-ci-pr-test.yml
  android/.gitignore
  android/app/build.gradle.kts
Labels: Fix, AN

#487 [AN] PlaceDetailPreviewFragment 뷰 구현
  android/app/src/main/java/com/daedan/festabook/presentation/common/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/PlaceDetailActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/adapter/PlaceNoticeAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeDetail/adapter/PlaceNoticeViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/CategoryView.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceCategoryUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/ClusterManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/MapManager.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/PlaceMapFragment.kt
  android/app/src/main/res/drawable/bg_gray050_stroke_gray200_radius_24dp.xml
  android/app/src/main/res/drawable/ic_bar_selected.xml
  android/app/src/main/res/drawable/ic_booth_selected.xml
  android/app/src/main/res/drawable/ic_food_truck_selected.xml
  android/app/src/main/res/drawable/ic_place_detail_host.xml
  android/app/src/main/res/drawable/ic_smoking_area_selected.xml
  android/app/src/main/res/drawable/ic_toilet_selected.xml
  android/app/src/main/res/drawable/ic_trash_selected.xml
  android/app/src/main/res/layout/activity_place_detail.xml
  android/app/src/main/res/layout/category_view.xml
  android/app/src/main/res/layout/fragment_place_detail_preview.xml
  android/app/src/main/res/layout/item_place_list.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
Labels: Feat, AN

#501 [BE] 공지사항 제목, 본문 검증 추가
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementTest.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementRequestFixture.java
  backend/src/test/java/com/daedan/festabook/announcement/dto/AnnouncementUpdateRequestFixture.java
Labels: BE

#524 refactor: dev 서버 nginx 사용할 수 있도록 was port 수정
  .github/workflows/backend-cd-dev.yml
Labels: CI/CD, BE

#526 [FE] dev 환경 배포 스크립트 nginx 정적 파일 서빙하도록 수정
  .github/workflows/frontend-ci-cd-dev.yml
Labels: CI/CD, FE

#494 [BE] Q&A 도메인을 FAQ 를 나타내도록 네이밍 수정
  backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java
  backend/src/main/java/com/daedan/festabook/question/controller/QuestionController.java
  backend/src/main/java/com/daedan/festabook/question/dto/QuestionAndAnswerUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/question/service/QuestionService.java
  backend/src/test/java/com/daedan/festabook/question/service/QuestionServiceTest.java
Labels: Refactor, BE

#509 [BE] 플레이스 공지사항 생성, 수정, 삭제 구현
  backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateResponse.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceAnnouncementJpaRepository.java
  backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java
  backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementTest.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceAnnouncementRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
Labels: Feat, BE

#445 [FE] 플레이스 수정 화면 구현
  .github/workflows/ci-cd-frontend-to-aws.yml
  .github/workflows/ci-cd-frontend.yml
  .github/workflows/frontend-ci-cd-dev.yml
  frontend/src/App.jsx
  frontend/src/components/common/Skeleton.jsx
  frontend/src/components/modals/AddImageModal.jsx
  frontend/src/components/modals/BoothModal.jsx
  frontend/src/components/modals/FestivalImagesModal.jsx
  frontend/src/components/modals/NoticeModal.jsx
  frontend/src/components/modals/PlaceEditModal.jsx
  frontend/src/components/modals/PlaceImagesModal.jsx
  frontend/src/components/modals/PlaceManageModal.jsx
  frontend/src/components/modals/PlaceNoticeModal.jsx
  frontend/src/contexts/AuthContext.jsx
  frontend/src/contexts/DataProvider.jsx
  frontend/src/data/categories.js
  frontend/src/pages/BoothsPage.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/LostFoundPage.jsx
  frontend/src/utils/api.js
  frontend/src/utils/cookies.js
Labels: FE

#535 [FE] S3 bucket을 가르키는 secret key에 prod_ prefix 추가
  .github/workflows/ci-cd-frontend-to-aws.yml
  .github/workflows/ci-cd-frontend.yml
Labels: CI/CD, FE

#548 [AN] 앱 초기 진입 시 분기 처리
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalLocalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalLocalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/ApiClient.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/FestaBookAuthInterceptor.kt
  android/app/src/main/java/com/daedan/festabook/presentation/explore/ExploreActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/PlaceMapFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/NavigationState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/splash/SplashViewModel.kt
Labels: Feat, AN

#543 [AN] 난독화 적용
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/main/java/com/daedan/festabook/FestaBookApp.kt
  android/app/src/main/java/com/daedan/festabook/logging/FirebaseAnalyticsTree.kt
  android/app/src/main/java/com/daedan/festabook/logging/FirebaseCrashlyticsTree.kt
  android/app/src/main/java/com/daedan/festabook/presentation/NotificationPermissionManager.kt
Labels: Feat, AN

#540 [AN] 학교 선택 화면 서버 통신 구현
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/AppPreferencesManager.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/DeviceLocalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/DeviceLocalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FcmDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FcmDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalLocalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalLocalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalNotificationLocalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/local/FestivalNotificationLocalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/festival/FestivalDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/festival/FestivalDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/UniversityResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/ExploreRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/FestivalNotificationRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/FestivalService.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/ExploreRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/explore/ExploreActivity.kt
  android/app/src/main/java/com/daedan/festabook/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/explore/SearchUiState.kt
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#574 [BE] 로그 파일을 날짜 기준이 아닌 크기 기준으로 변경
  backend/src/main/resources/logback-spring.xml
Labels: BE, Common

#567 [AN] 디버그 빌드와 릴리즈 빌드에 따라 baseUrl 분기처리
  .github/workflows/android-ci-pr-test.yml
  android/app/build.gradle.kts
Labels: Feat, AN

#568 [AN] 지도 화면에서 뒤로가기가 안먹는 문제 해결
  android/app/src/main/java/com/daedan/festabook/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/explore/SearchUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewSecondaryFragment.kt
Labels: Fix, AN

#583 [AN]안드로이드 디렉토리 변경 시에만 CI 빌드 트리거되도록 yml 설정 변경
  .github/workflows/android-ci-pr-test.yml
Labels: CI/CD, AN

#589 [BE] cloudFront 경유해 s3를 접근하도록 상대경로 응답 변경
  backend/src/main/java/com/daedan/festabook/storage/dto/StorageUploadResponse.java
  backend/src/main/java/com/daedan/festabook/storage/infrastructure/MockStorageManager.java
  backend/src/main/java/com/daedan/festabook/storage/infrastructure/S3StorageManager.java
  backend/src/main/java/com/daedan/festabook/storage/service/ImageStoreService.java
  backend/src/test/java/com/daedan/festabook/storage/service/ImageStoreServiceTest.java
Labels: Feat, BE

#594 [AN] 홈화면 라인업 뷰 UI 구현 (New)
  android/app/src/main/java/com/daedan/festabook/data/repository/FestivalRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/domain/model/LineupItem.kt
  android/app/src/main/java/com/daedan/festabook/domain/repository/FestivalRepository.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/LineupItemUiModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/LineupUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/LineupAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/LineupItemViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/PosterAdapter.kt
  android/app/src/main/res/drawable/bg_stroke_gray300_radius50dp.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_home_lineup.xml
  android/app/src/main/res/layout/item_home_poster.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/daedan/festabook/home/HomeTestFixture.kt
  android/app/src/test/java/com/daedan/festabook/home/HomeViewModelTest.kt
Labels: Feat, AN

#585 [AN] 일정화면 로딩 형태 변경
  android/app/src/main/java/com/daedan/festabook/data/model/response/lostitem/LostItemResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/lostitem/LostItemStatusSerializer.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/BindingAdapter.kt
  android/app/src/main/java/com/daedan/festabook/presentation/common/ImageUtil.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/adapter/PosterItemViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/news/lost/adapter/LostItemViewHolder.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeDetailPreview/PlaceDetailPreviewSecondaryFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/schedule/ScheduleTabPageFragment.kt
  android/app/src/main/res/drawable/img_fallback.jpeg
  android/app/src/main/res/layout/fragment_schedule.xml
  android/app/src/main/res/layout/fragment_schedule_tab_page.xml
  android/app/src/main/res/layout/item_schedule_tab_page_skeleton.xml
  android/app/src/main/res/layout/item_schedule_tab_skeleton.xml
  android/app/src/main/res/raw/loading.json
Labels: Refactor, AN

#592 [AN] 홈 다이얼로그 구현
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/res/drawable/ic_alarm.xml
  android/app/src/main/res/layout/main_alarm_view.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: Feat, AN

#609 [FE] 지도 페이지에 카테고리 추가
  frontend/src/components/map/MapSelector.tsx
  frontend/src/data/categories.js
  frontend/src/pages/MapSettingsPage.jsx
Labels: Feat, FE

#606 [BE] 오늘의 라인업 UD API 생성
  backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java
  backend/src/main/java/com/daedan/festabook/lineup/controller/LineupController.java
  backend/src/main/java/com/daedan/festabook/lineup/domain/Lineup.java
  backend/src/main/java/com/daedan/festabook/lineup/dto/LineupUpdateRequest.java
  backend/src/main/java/com/daedan/festabook/lineup/service/LineupService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/lineup/controller/LineupControllerTest.java
  backend/src/test/java/com/daedan/festabook/lineup/domain/LineupFixture.java
  backend/src/test/java/com/daedan/festabook/lineup/domain/LineupTest.java
  backend/src/test/java/com/daedan/festabook/lineup/dto/LineupUpdateRequestFixture.java
  backend/src/test/java/com/daedan/festabook/lineup/service/LineupServiceTest.java
Labels: Feat, BE

#608 [FE] 오늘의 라인업 화면 생성
  frontend/src/App.jsx
  frontend/src/components/modals/LineupAddModal.jsx
  frontend/src/components/modals/LineupEditModal.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/utils/api.js
Labels: Feat, FE

#611 [FE] CloudFront 캐시 무효화 추가
  .github/workflows/frontend-ci-cd-dev.yml
  .github/workflows/frontend-ci-cd-prod.yml
Labels: Feat, FE

#593 [AN] prod/android 브랜치 분리 및 cd 스크립트 작성
  .github/workflows/android-cd.yml
  .github/workflows/android-ci.yml
Labels: CI/CD, AN

#605 [AN] 홈 화면에서 일정 확인하기 버튼 클릭 시 일정 화면으로 이동
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/main/MainActivity.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/values/strings.xml
Labels: Feat, AN

#613 [AN] 홈 - 라인업 서버 연결
  android/app/src/main/java/com/daedan/festabook/AppContainer.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/lineup/LineupDataSource.kt
  android/app/src/main/java/com/daedan/festabook/data/datasource/remote/lineup/LineupDataSourceImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/model/response/lineup/LineupResponse.kt
  android/app/src/main/java/com/daedan/festabook/data/repository/FestivalRepositoryImpl.kt
  android/app/src/main/java/com/daedan/festabook/data/service/FestivalLineupService.kt
  android/app/src/main/java/com/daedan/festabook/data/service/api/ApiClient.kt
  android/app/src/main/res/layout/item_home_lineup.xml
  android/app/src/main/res/values/styles.xml
Labels: Feat, AN

#610 [BE] dev 환경에서 이미지 저장 기능 확인할 수 있도록 수정
  .github/workflows/backend-cd-dev.yml
  backend/src/main/java/com/daedan/festabook/storage/infrastructure/LocalStorageManager.java
  backend/src/main/java/com/daedan/festabook/storage/infrastructure/MockStorageManager.java
  backend/src/test/java/com/daedan/festabook/storage/infrastructure/LocalStorageManagerTest.java
  backend/src/test/java/com/daedan/festabook/storage/infrastructure/S3StorageManagerTest.java
Labels: Feat, BE

#603 [BE] 콘솔에서는 로그를 텍스트로 출력하도록 변경
  backend/src/main/resources/logback-spring.xml
Labels: Feat, BE

#622 [FE] api-host를 env로 변경
  frontend/src/utils/api.js
Labels: Fix, FE

#625 [BE] festivalId 응답값 추가 Hotifx
  backend/src/main/java/com/daedan/festabook/council/dto/CouncilLoginResponse.java
  backend/src/main/java/com/daedan/festabook/council/service/CouncilService.java
  backend/src/test/java/com/daedan/festabook/council/controller/CouncilControllerTest.java
  backend/src/test/java/com/daedan/festabook/council/service/CouncilServiceTest.java
Labels: Feat, BE

#626 [FE] login response에 담겨서 오는 festivalId를 LocalStorage에 저장
  frontend/src/auth/councilAuth.js
Labels: Fix, FE

#628 [BE] 라인업 GET 화이트리스트 등록 Hotifx
  backend/src/main/java/com/daedan/festabook/global/security/config/SecurityConfig.java
Labels: Feat, BE

#629 [COMMON] Noti Submitted 리뷰어 멘션 삭제
  .github/workflows/common-slack-notify-submitted.yml
Labels: Refactor, Common

#619 [BE] DB Soft Delete 구현
  backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java
  backend/src/main/java/com/daedan/festabook/council/domain/Council.java
  backend/src/main/java/com/daedan/festabook/device/domain/Device.java
  backend/src/main/java/com/daedan/festabook/event/domain/Event.java
  backend/src/main/java/com/daedan/festabook/event/domain/EventDate.java
  backend/src/main/java/com/daedan/festabook/festival/domain/Festival.java
  backend/src/main/java/com/daedan/festabook/festival/domain/FestivalImage.java
  backend/src/main/java/com/daedan/festabook/festival/domain/FestivalNotification.java
  backend/src/main/java/com/daedan/festabook/festival/infrastructure/FestivalImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/global/domain/BaseEntity.java
  backend/src/main/java/com/daedan/festabook/lineup/domain/Lineup.java
  backend/src/main/java/com/daedan/festabook/lostitem/domain/LostItem.java
  backend/src/main/java/com/daedan/festabook/place/domain/Place.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceFavorite.java
  backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java
  backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java
  backend/src/main/java/com/daedan/festabook/question/domain/Question.java
  backend/src/main/java/com/daedan/festabook/question/infrastructure/QuestionJpaRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/council/domain/CouncilFixture.java
  backend/src/test/java/com/daedan/festabook/device/domain/DeviceFixture.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventDateFixture.java
  backend/src/test/java/com/daedan/festabook/event/domain/EventFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalImageFixture.java
  backend/src/test/java/com/daedan/festabook/festival/domain/FestivalNotificationFixture.java
  backend/src/test/java/com/daedan/festabook/global/domain/BaseEntityTest.java
  backend/src/test/java/com/daedan/festabook/global/fixture/BaseEntityTestHelper.java
  backend/src/test/java/com/daedan/festabook/lineup/domain/LineupFixture.java
  backend/src/test/java/com/daedan/festabook/lostitem/domain/LostItemFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFavoriteFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java
  backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
  backend/src/test/java/com/daedan/festabook/question/domain/QuestionFixture.java
Labels: Feat, BE

#590 [BE] DDL 스크립트 자동화 툴 도입 및 데이터베이스 flyaway 계정 분리
  .github/workflows/backend-cd-dev.yml
  backend/build.gradle
  backend/src/main/java/com/daedan/festabook/global/config/FlywayConfig.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/db/migration/V1__init.sql
  backend/src/test/java/com/daedan/festabook/global/security/config/SecurityConfigTest.java
  backend/src/test/resources/application.yml
Labels: Feat, BE

#641 [FE] 이미지 업로드 api 연동/ Q&A 표현 FAQ로 변경
  frontend/src/App.jsx
  frontend/src/components/layout/Sidebar.jsx
  frontend/src/components/modals/AddImageModal.jsx
  frontend/src/components/modals/FaqModal.jsx
  frontend/src/components/modals/FestivalImagesModal.jsx
  frontend/src/components/modals/LineupAddModal.jsx
  frontend/src/components/modals/LineupEditModal.jsx
  frontend/src/components/modals/LostItemModal.jsx
  frontend/src/components/modals/PlaceImagesModal.jsx
  frontend/src/contexts/DataProvider.jsx
  frontend/src/pages/FaqPage.jsx
  frontend/src/utils/api.js
  frontend/src/utils/imageUpload.js
Labels: Feat, FE

#634 [BE] 다른 테스트에서 사용하는 계정 사용 변경
  backend/src/test/java/com/daedan/festabook/global/security/config/SecurityConfigTest.java
Labels: Fix, BE

#645 [BE] build할 때, sudo 권한 제공
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
Labels: CI/CD, BE

#647 [AN] 공지 클릭 안되는 문제 및 이미지 로딩 전략 변경
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListChildViewModel.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceListUiState.kt
  android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/PlaceMapFragment.kt
  android/app/src/main/java/com/daedan/festabook/util/FestabookGlobalExceptionHandler.kt
  android/app/src/main/res/layout/fragment_place_list.xml
  android/app/src/main/res/layout/item_place_list_skeleton.xml
Labels: Feat, AN

#661 [BE] dev cd workflow에서 캐싱 작업 제거
  .github/workflows/backend-cd-dev.yml
Labels: Feat, BE

#666 [BE] dev cd 파이프라인 실패하더라도 git actions는 성공하는 문제
  .github/workflows/backend-cd-dev.yml
Labels: CI/CD, BE
